name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-22.04

    services:
      db:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: chess_realtime_server_test
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    defaults:
      run:
        working-directory: server/chess_realtime_server

    env:
      MIX_ENV: test
      DATABASE_URL: "ecto://postgres:postgres@localhost:5432/chess_realtime_server_test"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15.2'
          otp-version: '26.0'

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: server/chess_realtime_server/deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install dependencies
        run: mix deps.get

      - name: Compile project
        run: mix compile --warnings-as-errors

      - name: Setup database
        run: |
          mix ecto.create
          mix ecto.migrate

      - name: Run tests
        run: mix test
